#yaml фалйы будут хранить конфигурацию приложения
#приложению нужно значть окружение в котором оно запущено,
#т.е. локальная ли это машина или удаленный север
#если удаленный сервер, то это может быть дев или прод(local,dev,prod)
env: "local"
storage_path: "./storage/storage.db" #путь к файлу базы данных
http_server: #отдельный объект с вложенными полями
  address: "localhost:8082" #адрес и порт сервера
  timeout: 4s #таймаут на чтение запроса и на ответ
  idle_timeout: 60s #таймаут жизни соединения с клиентом